### ISSUE TITLE
[FYI] `qh3` is now available from ArchLinux User Repository as `python-qh3-bin`

### ISSUE THREAD

**Issue by kseistrup** [jawah/qh3#22]
[ This is an informational message only. No action is required on your part, and the issue can be closed at your discretion. ]

I thought you'd like to know that ArchLinux users can now install `qh3` directly from ArchLinux User Repository (AUR) as `python-qh3-bin`:

+ https://aur.archlinux.org/packages/python-qh3-bin

The package can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g. `yay`:

```sh
» yay -S python-qh3-bin
```

This will fetch the current binary distribution for x86_64 from PyPI, and install it along with the LICENSE.

:pray:

**Comment by Ousret** [comment]
Dully noted. Thank you.
